### ISSUE TITLE
Standard admin interface implementation

### ISSUE THREAD

**Issue by toml01** [scrtlabs/secret-toolkit#12]
Implementation of common actions an admin can do in a contract:
* Stop
* Resume
* Change admin
* ..

Ideally this would also implement the underlying action of these messages - e.g. encapsulate saving to storage, etc..

**Comment by reuvenpo** [comment]
@toml01 Is this basically resolved by the `features` feature?

**Comment by toml01** [comment]
Huh, basically yes.
Not the admin stuff, but good enough for now imo

**Comment by reuvenpo** [comment]
Yeah... I think we can close this for now.
