### ISSUE TITLE
Panic! when trying to revoke_permit(Branch cw-v1.0)

### ISSUE THREAD

**Issue by itsHaseebSaeed** [scrtlabs/secret-toolkit#62]
Secret-toolkit's(Branch = cosmwasm-v1.0) revoke-permit functions panics because apparently, you cannot store an empty value in the storage.
[Here's](https://github.com/scrtlabs/secret-toolkit/blob/0d5f2bf79b5c21582ea7a4dc87fd60c1431ab5a6/packages/permit/src/state.rs#L25) the revoke_permit function that is trying to store an empty value.
Cw-0.10 doesn't have this condition  [before](https://github.com/CosmWasm/cosmwasm/blob/989cda3c85aa4236bbb9db68282f7c5b8c7f3ee0/packages/std/src/storage.rs#L76). Seems like it was added after version 0.10. This check [here](https://github.com/CosmWasm/cosmwasm/blob/6082e8a35a193f1365cb3367f77bd87c593a7ae4/packages/std/src/storage.rs#L30) is causing this error.

 I suggest we store permit name or any random value to avoid this error.

**Comment by toml01** [comment]
Good catch thanks @itsHaseebSaeed !

**Comment by itsHaseebSaeed** [comment]
Error resolved
